import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState,refundBalance,customerCreditPayable,cashflow,metrics,returnInventoryCost,validateRelations,type State } from '../lib/crm.ts';
import { financialPeriod,periodSalesBreakdown } from '../lib/financial-reporting.ts';
import { prepareReturnSettlement } from '../lib/return-settlement.ts';
import { prepareCustomerRefund } from '../lib/customer-refunds.ts';
import { validateWorkspaceChange,visibleState } from '../lib/role-data.ts';
import { parsePageRequest } from '../lib/pagination.ts';
function fixture(){const s=initialState(),productId=s.products[0].id;s.customers=[{id:'c',name:'Customer',phone:'',address:'',city:'',preference:'',notes:'',consent:false,created:'2026-01-01'}];s.batches=[{id:'b',productId,qty:10,unitCost:500,received:'2026-01-01',expiry:'2099-12-31',supplierId:'',invoice:'',payments:[],paid:false}];s.orders=[{id:'o',number:'1001',customerId:'c',created:'2026-01-01',delivered:'2026-01-02',returnedAt:'2026-02-05',status:'Returned',payment:'Bank',channel:'Website',items:[{productId,qty:1,price:1000,allocations:[{batchId:'b',qty:1,unitCost:500}]}],discount:0,deliveryCharge:0,courierCost:50,packaging:0,paymentFee:0,returnFee:20,settled:true,settledAt:'2026-01-03',collections:[{id:'p',date:'2026-01-03',amount:1000,reference:'original'}],restocked:false,tracking:'',notes:''}];s.accountOpenings=[{account:'bank',date:'2026-01-01',balance:0}];s.accountMatches=[{entryId:'order-collection-o-p',account:'bank',matched:true,reference:'original'}];return s;}
const decision={id:'r',orderId:'o',date:'2026-02-06',kind:'No refund' as const,amount:0,reason:'Customer agreement'};
test('agreed no-refund outcome clears payable without cash payout and preserves stock costs',()=>{const s=fixture(),next=prepareReturnSettlement(s,decision);assert.equal(refundBalance(next,next.orders[0]),0);assert.deepEqual(cashflow(next),cashflow(s));assert.equal(metrics(next).profit,metrics(s).profit+1000);assert.equal(returnInventoryCost(next,next.orders[0]),500);assert.equal(prepareReturnSettlement(next,decision),next);assert.throws(()=>prepareReturnSettlement(next,{...decision,id:'another'}),/already/);});
test('reduced agreed refund leaves only the agreed balance payable',()=>{const s=prepareReturnSettlement(fixture(),{...decision,kind:'Refund',amount:400});assert.equal(refundBalance(s,s.orders[0]),400);const next=prepareCustomerRefund(s,{id:'pay',orderId:'o',date:'2026-02-06',amount:400,account:'bank',reference:'',reason:'Agreed refund'},'finance');assert.equal(refundBalance(next,next.orders[0]),0);assert.equal(metrics(next).profit,metrics(s).profit);assert.throws(()=>prepareCustomerRefund(s,{id:'bad',orderId:'o',date:'2026-02-06',amount:401,account:'bank',reference:'',reason:'Overpayment'},'finance'),/exceeds/);});
test('store and exchange credits remain liabilities and applying one does not create cash',()=>{for(const kind of ['Store credit','Exchange'] as const){const s=prepareReturnSettlement(fixture(),{...decision,kind,amount:1000});assert.equal(customerCreditPayable(s),1000);assert.equal(refundBalance(s,s.orders[0]),0);s.orders.push({...structuredClone(s.orders[0]),id:'replacement',number:'1002',created:'2026-02-06',delivered:undefined,returnedAt:undefined,status:'New',collections:[],settled:false,settledAt:undefined,returnFee:0});const originalCash=cashflow(s);s.creditUses.push({id:'u',settlementId:'r',orderId:'replacement',date:'2026-02-06',amount:1000});s.orders[1].collections.push({id:'credit-u',date:'2026-02-06',amount:1000,reference:'Credit'});validateRelations(s);assert.equal(customerCreditPayable(s),0);assert.deepEqual(cashflow(s),originalCash);s.creditUses.push({id:'excess',settlementId:'r',orderId:'replacement',date:'2026-02-06',amount:1});assert.throws(()=>validateRelations(s),/overused/);}});
test('a later return preserves original month revenue and records a later sales reversal',()=>{const s=fixture();assert.equal(financialPeriod(s,'2026-01').revenue,1000);assert.equal(financialPeriod(s,'2026-01').profit,450);assert.equal(financialPeriod(s,'2026-02').revenue,-1000);assert.equal(financialPeriod(s,'2026-02').profit,-1020);});
test('damaged inspection retains cost while sellable and quarantined inspection recover it on the inspection date',()=>{for(const outcome of ['Damaged','Sellable','Quarantine'] as const){const s=fixture();s.orders[0].restocked=true;s.returnInspections=[{id:'i',orderId:'o',date:'2026-03-01',outcome}];assert.equal(returnInventoryCost(s,s.orders[0]),outcome==='Damaged'?500:0);assert.equal(financialPeriod(s,'2026-01').profit,450);assert.equal(financialPeriod(s,'2026-02').profit,-1020);assert.equal(financialPeriod(s,'2026-03').profit,outcome==='Damaged'?0:500);assert.equal(['2026-01','2026-02','2026-03'].reduce((n,m)=>n+financialPeriod(s,m).profit,0),metrics(s).profit);}});
test('later quarantine damage is a later dated writeoff and does not rewrite original inspection recovery',()=>{const s=fixture();s.orders[0].restocked=true;s.returnInspections=[{id:'i',orderId:'o',date:'2026-03-01',outcome:'Quarantine'},{id:'d',orderId:'o',date:'2026-04-01',outcome:'Damaged',event:'Written off',amount:500}];validateRelations(s);assert.equal(returnInventoryCost(s,s.orders[0]),500);assert.equal(financialPeriod(s,'2026-03').profit,500);assert.equal(financialPeriod(s,'2026-04').profit,-500);assert.equal(['2026-01','2026-02','2026-03','2026-04'].reduce((n,m)=>n+financialPeriod(s,m).profit,0),metrics(s).profit);});
test('settlements require valid amounts and dates and cannot be forged through generic saves',()=>{const s=fixture();for(const change of [{amount:1001,kind:'Refund'},{date:'2026-01-01'},{amount:1}])assert.throws(()=>prepareReturnSettlement(s,{...decision,...change}));const next=prepareReturnSettlement(s,decision);assert.throws(()=>validateWorkspaceChange(s,next),/dedicated/);const deleted=structuredClone(next);deleted.returnSettlements=[];assert.throws(()=>validateWorkspaceChange(next,deleted),/history/);assert.equal(visibleState(next,'sales').returnSettlements.length,0);});
test('paid cancelled orders can be settled and refunded without a returned-stock inspection',()=>{const s=fixture();s.orders[0].status='Cancelled';s.orders[0].returnedAt=undefined;s.orders[0].delivered=undefined;const next=prepareReturnSettlement(s,decision);assert.equal(refundBalance(next,next.orders[0]),0);});
test('pagination rejects oversized and invalid bounds and keeps unpaginated compatibility',()=>{assert.equal(parsePageRequest('https://example.test/api/orders'),undefined);assert.deepEqual(parsePageRequest('https://example.test/api/orders?page=2&pageSize=25&q=abc'),{page:2,pageSize:25,q:'abc',status:'All'});for(const query of ['page=0','pageSize=201','page=1.5','page=-1','page=10001'])assert.throws(()=>parsePageRequest('https://example.test/?'+query));});

test('channel and product totals follow dated returns and allocate product discounts',()=>{const s=fixture();s.orders[0].discount=100;const january=periodSalesBreakdown(s,'2026-01'),february=periodSalesBreakdown(s,'2026-02');assert.equal(january.channels[0].revenue,900);assert.equal(january.products[0].revenue,900);assert.equal(february.channels[0].revenue,-900);assert.equal(february.products[0].units,-1);});
