import test from 'node:test';
import assert from 'node:assert/strict';
import { compactWorkspace } from '../lib/workspace-projection.ts';
import { workspaceSearch } from '../lib/workspace-search.ts';
import { visibleState } from '../lib/role-data.ts';
import { literalLike,parsePageRequest } from '../lib/pagination.ts';
import { initialState,type Order } from '../lib/crm.ts';
function largeWorkspace(){const s=initialState();s.customers=Array.from({length:70},(_,i)=>({id:'c'+i,name:'Customer '+i,phone:'',address:'',city:'Dhaka',preference:'',notes:'',consent:false,created:'2026-01-01'}));s.batches=[{id:'b',productId:s.products[0].id,qty:100,unitCost:100,received:'2026-01-01',expiry:'2099-12-31',supplierId:'',invoice:'',payments:[],paid:false}];s.orders=s.customers.map((c,i)=>({id:'o'+i,number:'ORDER-'+String(i).padStart(3,'0'),customerId:c.id,created:'2026-01-01',delivered:'2026-01-02',status:'Delivered',channel:'Website',payment:'Bank',discount:0,deliveryCharge:0,courierCost:0,paymentFee:0,packaging:0,returnFee:0,settled:false,restocked:false,tracking:'',notes:'',collections:[],items:[{productId:s.products[0].id,qty:1,price:500,allocations:[{batchId:'b',qty:1,unitCost:100}]}]} as Order));return s;}
test('compact bootstrap bounds raw records but preserves totals and complete reporting',()=>{const s=largeWorkspace(),p=compactWorkspace(s,'owner','2026-01','7');assert.equal(p.data.orders.length,5);assert.ok(p.data.customers.length<=5);assert.equal(p.summary.orderStats.total,70);assert.equal(p.summary.overview.customerCount,70);assert.equal(p.summary.report?.reportOrders.length,70);assert.equal(p.summary.report?.reportRevenue,35000);assert.equal(p.summary.report?.reportProfit,28000);assert.deepEqual(p.summary.report?.reportOrders,{length:70});assert.equal(p.data.batches.length,0);assert.equal(p.data.expenses.length,0);assert.ok(JSON.stringify(p).length<JSON.stringify(s).length);});
test('bounded global search reaches records outside the first page',()=>{const s=largeWorkspace();assert.equal(workspaceSearch(s,'owner','order-069')[0].detail?.id,'o69');assert.equal(workspaceSearch(s,'owner','customer').length,18);assert.equal(workspaceSearch(visibleState(s,'inventory'),'inventory','customer').length,0);});
test('compact staff bootstrap does not expose management reports or supplier costs',()=>{const s=largeWorkspace(),p=compactWorkspace(visibleState(s,'sales'),'sales','2026-01');assert.equal(p.summary.report,undefined);assert.ok(p.data.orders.every(o=>o.items.every(i=>i.allocations.every(a=>a.unitCost===0))));assert.equal(p.data.suppliers.length,0);});
test('search terms treat SQL wildcards literally and customer history has bounded query input',()=>{assert.equal(literalLike('100%_\\'),'%'+'100\\%\\_\\\\'+'%');assert.equal(parsePageRequest('https://x.test/?page=1&pageSize=25&customerId=c69')?.customerId,'c69');assert.throws(()=>parsePageRequest('https://x.test/?page=1&customerId='+('a'.repeat(121))));});
