'use client';
import React,{useState} from 'react';
import { Input } from '@/components/ui/input';
export default function AuthForm({mode,token=''}:{mode:'login'|'invite'|'setup';token?:string}){
  const [name,setName]=useState(''),[secret,setSecret]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode!=='login'&&password!==confirm){setError('Passwords do not match.');return}setBusy(true);try{const r=await fetch(mode==='invite'?'/api/auth/accept':mode==='setup'?'/api/auth/setup':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='invite'?{token,password}:mode==='setup'?{name,email,password,secret}:{email,password})});const data:any=await r.json();if(!r.ok)throw Error(data.error||'Could not sign in.');window.location.assign('/')}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
  return <main className="auth-layout"><section className="auth-card"><div className="auth-brand"><img src="/aloyri-logo.webp" alt="ALOYRI — Let Your Skin Glow" /></div><h1>{mode==='invite'?'Set your password':mode==='setup'?'Set up your owner account':'Sign in to ALOYRI'}</h1><p>{mode==='invite'?'Create your password to access the ALOYRI workspace.':mode==='setup'?'Enter the setup key configured for this workspace.':'Manage orders, inventory, customers and finances in one secure workspace.'}</p><form onSubmit={submit}>{mode==='setup'&&<><label>Your name<Input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Setup key<Input type="password" required value={secret} onChange={e=>setSecret(e.target.value)}/></label></>}{mode!=='invite'&&<label>Email address<Input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>Password<Input type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?undefined:12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode!=='login'&&<label>Confirm password<Input type="password" autoComplete="new-password" minLength={12} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy}>{busy?'Please wait…':mode==='invite'?'Create account':mode==='setup'?'Create owner account':'Sign in'}</button></form>{mode==='invite'?<a href="/login">Already have an account? Sign in</a>:mode==='setup'?<small>Owner setup can be completed once.</small>:<><a href="/forgot-password">Forgot password?</a><small>Need access? Contact your workspace owner.</small></>}</section></main>
}

