'use client';
import React,{useState} from 'react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
export default function ChangePassword({open,onClose}:{open:boolean;onClose:()=>void}){
  const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(next!==confirm){setError('Passwords do not match.');return}setBusy(true);try{const response=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({current,next})});const data:any=await response.json();if(!response.ok)throw Error(data.error||'Could not update password.');window.location.assign('/login')}catch(e){setError(e instanceof Error?e.message:'Could not update password.')}finally{setBusy(false)}}
  return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>Change password</DialogTitle><DialogDescription>You will sign in again after saving.</DialogDescription></DialogHeader><form className="record-form" onSubmit={submit}><div className="field"><label>Current password<Input type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></label></div><div className="field"><label>New password<Input type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={next} onChange={e=>setNext(e.target.value)}/></label></div><div className="field"><label>Confirm new password<Input type="password" autoComplete="new-password" minLength={12} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="btn secondary" type="button" onClick={onClose}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving…':'Save password'}</button></div></form></DialogContent></Dialog>
}
