'use client';

import { useState } from 'react';
import { toast } from 'sonner';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { accountIds,accountNames,customerPaidAmount,customerRefundPayable,dateLabel,refundBalance,refundedAmount,taka,today,uid,type State } from '@/lib/crm';
import { Empty } from './crm-ui';

type Refund=State['customerRefunds'][number];
type Props={state:State;canManage:boolean;busy:boolean;onPost:(refund:Refund)=>Promise<void>};
export default function CustomerRefunds({state:s,canManage,busy,onPost}:Props){
 const [form,setForm]=useState<Refund|null>(null),[posting,setPosting]=useState(false);
 const orders=s.orders.filter(o=>o.status==='Returned'&&customerPaidAmount(o)>0);
 const update=(change:Partial<Refund>)=>setForm(f=>f?{...f,...change,id:uid()}:f);
 async function submit(event:React.FormEvent){event.preventDefault();if(!form||posting)return;setPosting(true);try{await onPost(form);setForm(null);toast.success('Customer refund recorded. Account balance and refund payable updated.')}catch(e){toast.error(e instanceof Error?e.message:'Could not record refund.')}finally{setPosting(false)}}
 return <>
  <section className="panel"><div className="panel-heading"><div><h2>Customer refunds</h2><p>Paid orders returned by customers. Record money actually paid back; stock inspection is separate.</p></div><strong>{taka(customerRefundPayable(s))} refund payable</strong></div>
   {orders.length?<Table><TableHeader><TableRow><TableHead>Order / customer</TableHead><TableHead>Customer paid</TableHead><TableHead>Refunded</TableHead><TableHead>Refund payable</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{orders.map(o=>{const due=refundBalance(s,o),paid=refundedAmount(s,o);return <TableRow key={o.id}><TableCell><strong>#{o.number}</strong><small className="cell-sub">{s.customers.find(c=>c.id===o.customerId)?.name||'Customer'}</small></TableCell><TableCell>{taka(customerPaidAmount(o))}</TableCell><TableCell>{taka(paid)}</TableCell><TableCell className="numeric">{taka(due)}</TableCell><TableCell>{due<=.001?'Refunded':paid>0?'Partially refunded':'Refund due'}</TableCell><TableCell>{canManage&&due>.001&&<button className="btn secondary small" disabled={busy||posting||!s.accountOpenings.length} onClick={()=>setForm({id:uid(),orderId:o.id,date:today(),amount:Math.round(due*100)/100,account:s.accountOpenings[0].account,reference:'',reason:''})}>Record refund</button>}</TableCell></TableRow>})}</TableBody></Table>:<Empty title="No customer refunds due" text="Return an order with a recorded customer payment to see its refund balance here."/>}
   <p className="form-note">A refund reduces cash and customer refund payable. It does not add an operating expense. Original collections remain in Cashflow. For fully settled COD, customer paid includes courier and payment fees withheld from your payout. Partial COD remittances use the amount recorded until settlement confirms full payment.</p>
   {canManage&&!s.accountOpenings.length&&<p className="form-note">Configure a paying account under Accounts before recording a refund.</p>}
  </section>
  <section className="panel"><div className="panel-heading"><div><h2>Refund payment history</h2><p>Recorded payouts retain their order, account, reference and reason.</p></div></div>{s.customerRefunds.length?<Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Order</TableHead><TableHead>Account</TableHead><TableHead>Reference / reason</TableHead><TableHead>Amount</TableHead></TableRow></TableHeader><TableBody>{[...s.customerRefunds].sort((a,b)=>b.date.localeCompare(a.date)).map(r=><TableRow key={r.id}><TableCell>{dateLabel(r.date)} {r.date.slice(0,4)}</TableCell><TableCell>#{s.orders.find(o=>o.id===r.orderId)?.number}</TableCell><TableCell>{accountNames[r.account]}</TableCell><TableCell>{r.reference||'—'}<small className="cell-sub">{r.reason}</small></TableCell><TableCell className="numeric">{taka(r.amount)}</TableCell></TableRow>)}</TableBody></Table>:<Empty title="No refunds recorded" text="Full and partial payments will appear here once recorded."/>}</section>
  <Dialog open={!!form} onOpenChange={open=>{if(!open&&!posting)setForm(null)}}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>Record customer refund</DialogTitle><DialogDescription>Record a payment already made to the customer. This does not send money through a payment provider.</DialogDescription></DialogHeader>{form&&<form onSubmit={submit} className="record-form"><p>Order #{s.orders.find(o=>o.id===form.orderId)?.number} · Remaining refund {taka(refundBalance(s,s.orders.find(o=>o.id===form.orderId)!))}</p><label>Amount<Input aria-label="Refund amount" className="choice native-choice" type="number" min="0.01" step="0.01" max={refundBalance(s,s.orders.find(o=>o.id===form.orderId)!)} required value={form.amount} disabled={posting} onChange={e=>update({amount:Number(e.target.value)})}/></label><label>Date<Input aria-label="Refund date" className="choice native-choice" type="date" max={today()} required value={form.date} disabled={posting} onChange={e=>update({date:e.target.value})}/></label><label>Paying account<select aria-label="Refund account" className="choice native-choice" value={form.account} disabled={posting} onChange={e=>update({account:e.target.value as typeof accountIds[number]})}>{s.accountOpenings.map(a=><option key={a.account} value={a.account}>{accountNames[a.account]}</option>)}</select></label><label>Payment reference<Input aria-label="Refund reference" className="choice native-choice" maxLength={200} value={form.reference} disabled={posting} onChange={e=>update({reference:e.target.value})}/></label><label>Reason<textarea aria-label="Refund reason" className="choice native-choice" required maxLength={2000} value={form.reason} disabled={posting} onChange={e=>update({reason:e.target.value})}/></label><div className="form-actions"><button className="btn secondary" type="button" disabled={posting} onClick={()=>setForm(null)}>Cancel</button><button className="btn primary" type="submit" disabled={posting||busy}>{posting?'Recording…':'Record refund payment'}</button></div></form>}</DialogContent></Dialog>
 </>;
}
