'use client';
import { useEffect,useState } from 'react';
import { Input } from '@/components/ui/input';
export default function RecoveryCodes(){
 const [remaining,setRemaining]=useState<number|null>(null),[password,setPassword]=useState(''),[codes,setCodes]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/auth/recovery-codes',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setRemaining(d.remaining)}).catch(()=>{if(active)setError('Recovery codes could not be loaded.')});return()=>{active=false}},[]);
 async function generate(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/recovery-codes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({current:password})}),d=await r.json();if(!r.ok)throw Error(d.error);setCodes(d.codes);setPassword('');setRemaining(d.codes.length)}catch(e){setError(e instanceof Error?e.message:'Could not create codes.')}finally{setBusy(false)}}
 function download(){const blob=new Blob(['ALOYRI account recovery codes\nKeep offline. Each code works once.\n\n'+codes.join('\n')],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='aloyri-recovery-codes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section><h3>Account recovery codes</h3><p>{remaining===null?'Checking codes…':remaining+' unused codes'} · Use a saved code from Forgot password if you lose access.</p><p className="form-note">Generating new codes replaces all older codes. Save them offline; they are shown only once.</p><form onSubmit={generate}><label>Current password<Input aria-label="Password for recovery codes" type="password" autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn secondary" disabled={busy}>{busy?'Generating…':'Generate recovery codes'}</button></form>{error&&<p role="alert">{error}</p>}{codes.length>0&&<><button className="btn secondary" onClick={download}>Download recovery codes</button><pre className="recovery-code-list">{codes.join('\n')}</pre></>}</section>;
}
