'use client';
import React,{useState} from 'react';
import { Check,Link2,Unlink2,ArrowRightLeft,Wallet } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { accountIds,accountNames,accountBalance,cashflow,dateLabel,today,uid,type State } from '@/lib/crm';

type Account=typeof accountIds[number];
type Movement=ReturnType<typeof cashflow>['entries'][number];
const signed=(entry:Movement)=>entry.kind==='in'?entry.amount:-entry.amount;
const bdt=(amount:number)=>'৳'+amount.toLocaleString('en-BD',{minimumFractionDigits:2,maximumFractionDigits:2});

export default function Reconciliation({state,busy,canEdit,onSave}:{state:State;busy:boolean;canEdit:boolean;onSave:(next:State)=>Promise<boolean>}){
  const [selected,setSelected]=useState<Account>('cash');
  const [openingDate,setOpeningDate]=useState(today());
  const [openingBalance,setOpeningBalance]=useState('0');
  const [statementDate,setStatementDate]=useState(today());
  const [statementBalance,setStatementBalance]=useState('');
  const [error,setError]=useState('');
  const [references,setReferences]=useState<Record<string,string>>({});
  const [transferFrom,setTransferFrom]=useState<Account>('cash');
  const [transferTo,setTransferTo]=useState<Account>('bank');
  const [transferAmount,setTransferAmount]=useState('');
  const [transferNote,setTransferNote]=useState('');
  const opening=state.accountOpenings.find(a=>a.account===selected);
  const entries=cashflow(state).entries;
  const links=new Map(state.accountMatches.map(m=>[m.entryId,m]));
  const assigned=opening?entries.filter(e=>links.get(e.id)?.account===selected&&e.date>=opening.date):[];
  const available=opening?entries.filter(e=>!links.has(e.id)&&e.date>=opening.date):[];
  const ledger=opening?opening.balance+assigned.reduce((sum,e)=>sum+signed(e),0):0;
  const matched=opening&&opening.statementDate?opening.balance+assigned.filter(e=>links.get(e.id)?.matched&&e.date<=opening.statementDate!).reduce((sum,e)=>sum+signed(e),0):0;
  const difference=opening?.statementBalance===undefined?null:opening.statementBalance-matched;

  async function update(mutator:(next:State)=>void){setError('');const next=structuredClone(state);mutator(next);if(!await onSave(next))setError('Change was not saved. Review the message above and try again.');}
  async function configureOpening(e:React.FormEvent){e.preventDefault();const amount=Number(openingBalance);if(!Number.isFinite(amount)||amount<0||openingDate>today()){setError('Enter a valid starting balance and a date no later than today.');return}await update(next=>next.accountOpenings.push({account:selected,date:openingDate,balance:amount}));}
  async function saveStatement(e:React.FormEvent){e.preventDefault();const amount=Number(statementBalance);if(!opening||statementBalance.trim()===''||!Number.isFinite(amount)||amount<0||statementDate<opening.date||statementDate>today()){setError('Enter a statement balance and a date from the opening date through today.');return}await update(next=>{const account=next.accountOpenings.find(a=>a.account===selected)!;account.statementDate=statementDate;account.statementBalance=amount;});}
  function changeAccount(value:string){setSelected(value as Account);setError('');setStatementBalance('');setStatementDate(today());setReferences({});}
  async function transfer(e:React.FormEvent){e.preventDefault();setError('');const amount=Number(transferAmount);if(transferFrom===transferTo){setError('Choose two different accounts.');return}if(!Number.isFinite(amount)||amount<=0){setError('Enter a transfer amount above zero.');return}const fromOpening=state.accountOpenings.find(a=>a.account===transferFrom),toOpening=state.accountOpenings.find(a=>a.account===transferTo);if(!fromOpening||!toOpening){setError('Set opening balances for both accounts before transferring.');return}const fromBalance=accountBalance(state,transferFrom);if(fromBalance!==null&&amount>fromBalance+.001){setError('Transfer exceeds the current CRM balance of '+accountNames[transferFrom]+'.');return}const transferId=uid(),outId=uid(),inId=uid(),description=(transferNote.trim()||'Account transfer')+' · '+accountNames[transferFrom]+' → '+accountNames[transferTo];await update(next=>{next.cashEntries.push({id:outId,date:today(),kind:'out',category:'Transfer',description,amount,transferId},{id:inId,date:today(),kind:'in',category:'Transfer',description,amount,transferId});next.accountMatches.push({entryId:'manual-'+outId,account:transferFrom,matched:false,reference:''},{entryId:'manual-'+inId,account:transferTo,matched:false,reference:''})});setTransferAmount('');setTransferNote('');}
  return <div className="reconciliation">
    <section className="panel"><div className="panel-heading"><div><h2>Accounts & cash management</h2><p>Live CRM balances for your operating accounts. Balances use each account opening plus movements assigned to that account.</p></div><Wallet size={20}/></div><div className="account-balance-grid">{accountIds.map(id=>{const balance=accountBalance(state,id),opening=state.accountOpenings.find(a=>a.account===id);return <button type="button" key={id} className={'account-balance-card '+(selected===id?'active':'')} onClick={()=>changeAccount(id)}><span>{accountNames[id]}</span><strong>{balance===null?'Not set':bdt(balance)}</strong><small>{opening?'Since '+dateLabel(opening.date):'Set opening balance below'}</small></button>})}</div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Transfer between accounts</h2><p>Creates linked cash-out and cash-in movements and assigns both sides automatically. A transfer changes account balances but not total business cashflow.</p></div><ArrowRightLeft size={20}/></div><form className="reconcile-form transfer-form" onSubmit={e=>void transfer(e)}><label>From<select className="choice native-choice" value={transferFrom} onChange={e=>setTransferFrom(e.target.value as Account)}>{accountIds.map(id=><option key={id} value={id}>{accountNames[id]}</option>)}</select></label><label>To<select className="choice native-choice" value={transferTo} onChange={e=>setTransferTo(e.target.value as Account)}>{accountIds.map(id=><option key={id} value={id}>{accountNames[id]}</option>)}</select></label><label>Amount (BDT)<Input type="number" min="0.01" step="0.01" required value={transferAmount} onChange={e=>setTransferAmount(e.target.value)}/></label><label>Reference / note<Input maxLength={200} value={transferNote} onChange={e=>setTransferNote(e.target.value)} placeholder="e.g. Cash deposit"/></label><button className="btn primary" type="submit" disabled={busy||!canEdit}><ArrowRightLeft size={15}/>Transfer</button></form></section>
    <section className="panel"><div className="panel-heading"><div><h2>Account reconciliation</h2><p>Assign each recorded payment to the account that actually received or paid it. Match it after checking your statement.</p></div></div>
      <div className="reconcile-account-tabs" role="group" aria-label="Reconciliation account">{accountIds.map(id=>{const a=state.accountOpenings.find(x=>x.account===id);const n=entries.filter(e=>state.accountMatches.some(m=>m.entryId===e.id&&m.account===id&&!m.matched)).length;return <button type="button" className={'btn '+(selected===id?'primary':'secondary')} key={id} onClick={()=>changeAccount(id)}>{accountNames[id]}{a&&n>0?` · ${n} to match`:''}</button>})}</div>
      {!opening?<form className="reconcile-form" onSubmit={e=>void configureOpening(e)}><p>Enter the real {accountNames[selected]} balance <strong>before</strong> transactions dated on the opening date. Earlier CRM movements will stay in Cashflow but will not affect this account.</p><label>Opening date<Input type="date" aria-label="Opening date" max={today()} required value={openingDate} onChange={e=>setOpeningDate(e.target.value)}/></label><label>Opening balance (BDT)<Input type="number" aria-label="Opening balance" min="0" step="0.01" required value={openingBalance} onChange={e=>setOpeningBalance(e.target.value)}/></label><button className="btn primary" type="submit" disabled={busy||!canEdit}>Set opening balance</button></form>:<><div className="reconcile-summary"><div><span>Opening balance · {dateLabel(opening.date)}</span><strong>{bdt(opening.balance)}</strong></div><div><span>Assigned movement</span><strong>{bdt(assigned.reduce((sum,e)=>sum+signed(e),0))}</strong></div><div><span>CRM account balance</span><strong>{bdt(ledger)}</strong></div></div><p className="form-note">The CRM balance uses assigned movements from {dateLabel(opening.date)} onward. It is an estimate until every relevant payment is assigned.</p>
        <form className="reconcile-form" onSubmit={e=>void saveStatement(e)}><label>Latest statement date<Input type="date" aria-label="Latest statement date" min={opening.date} max={today()} required value={statementDate} onChange={e=>setStatementDate(e.target.value)}/></label><label>Actual statement balance (BDT)<Input type="number" aria-label="Actual statement balance" min="0" step="0.01" required value={statementBalance} onChange={e=>setStatementBalance(e.target.value)}/></label><button className="btn secondary" type="submit" disabled={busy||!canEdit}>Compare balance</button></form>
        {difference!==null&&<div className="reconcile-result"><span>Statement on {dateLabel(opening.statementDate!)}: <strong>{bdt(opening.statementBalance!)}</strong></span><span>Opening + matched movements through that date: <strong>{bdt(matched)}</strong></span><strong>{Math.abs(difference)<0.01?'Matched balance agrees':`Difference: ${bdt(difference)}`}</strong><small>Unmatched movements are excluded from this comparison. A zero difference does not confirm that every payment was assigned.</small></div>}</>}
      {error&&<p className="form-error" role="alert">{error}</p>}
    </section>
    {opening&&<><section className="panel"><div className="panel-heading"><div><h2>{accountNames[selected]} movements</h2><p>Use the reference for a transaction ID, bank statement line, or wallet payment number.</p></div></div>{assigned.length?<Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Movement</TableHead><TableHead>Amount</TableHead><TableHead>Reference</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{assigned.map(e=>{const link=links.get(e.id)!;return <TableRow key={e.id}><TableCell>{dateLabel(e.date)}</TableCell><TableCell>{e.source}<small className="cell-sub">{e.description}</small></TableCell><TableCell>{e.kind==='in'?'+':'−'} {bdt(e.amount)}</TableCell><TableCell><div className="reconcile-actions"><Input aria-label={'Reference for '+e.description} value={references[e.id]??link.reference} maxLength={200} disabled={busy||!canEdit} placeholder="Statement reference" onChange={event=>setReferences(current=>({...current,[e.id]:event.target.value}))}/><button type="button" className="btn secondary small" disabled={busy||!canEdit||(references[e.id]??link.reference).trim()===link.reference} onClick={()=>void update(next=>{next.accountMatches.find(m=>m.entryId===e.id)!.reference=(references[e.id]??'').trim()})}>Save</button></div></TableCell><TableCell><div className="reconcile-actions"><button type="button" className={'btn small '+(link.matched?'secondary':'primary')} disabled={busy||!canEdit} onClick={()=>void update(next=>{const match=next.accountMatches.find(m=>m.entryId===e.id)!;match.matched=!link.matched;match.reference=(references[e.id]??match.reference).trim()})}><Check size={14}/>{link.matched?'Matched':'Mark matched'}</button><button type="button" className="icon-button" aria-label={'Unassign '+e.description} title="Unassign movement" disabled={busy||!canEdit} onClick={()=>void update(next=>{next.accountMatches=next.accountMatches.filter(m=>m.entryId!==e.id)})}><Unlink2 size={16}/></button></div></TableCell></TableRow>})}</TableBody></Table>:<p className="form-note">No movements assigned to {accountNames[selected]} yet.</p>}</section>
      <section className="panel"><div className="panel-heading"><div><h2>Unassigned cash movements</h2><p>Choose the account where the money actually moved. Payment method alone does not determine the payout account.</p></div></div>{available.length?<Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Movement</TableHead><TableHead>Amount</TableHead><TableHead>Account</TableHead></TableRow></TableHeader><TableBody>{available.map(e=><TableRow key={e.id}><TableCell>{dateLabel(e.date)}</TableCell><TableCell>{e.source}<small className="cell-sub">{e.description}</small></TableCell><TableCell>{e.kind==='in'?'+':'−'} {bdt(e.amount)}</TableCell><TableCell><button type="button" className="btn secondary small" disabled={busy||!canEdit} onClick={()=>void update(next=>{next.accountMatches.push({entryId:e.id,account:selected,matched:false,reference:''})})}><Link2 size={14}/>Assign to {accountNames[selected]}</button></TableCell></TableRow>)}</TableBody></Table>:<p className="form-note">No unassigned movements dated on or after this account’s opening date.</p>}</section></>}
    <p className="form-note">Order settlements, paid stock purchases, and expenses appear automatically from Cashflow. Use Transfer between accounts instead of entering transfers manually. It creates and assigns both sides together. Do not add a payment again just to reconcile it.</p>
  </div>;
}
