'use client';
import { useState } from 'react';
import { toast } from 'sonner';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { creditBalance,customerCreditPayable,customerPaidAmount,orderBalance,refundedAmount,taka,today,uid,type State } from '@/lib/crm';
type Settlement=State['returnSettlements'][number];
type Props={state:State;canManage:boolean;busy:boolean;onAction:(action:'settlement'|'credit',payload:unknown,orderId?:string)=>Promise<void>};
export default function ReturnSettlements({state:s,canManage,busy,onAction}:Props){
 const [decision,setDecision]=useState<Settlement|null>(null),[credit,setCredit]=useState<State['creditUses'][number]|null>(null),[posting,setPosting]=useState(false);
 const returns=s.orders.filter(o=>['Returned','Cancelled'].includes(o.status)&&customerPaidAmount(o)>0);
 const source=credit&&s.returnSettlements.find(r=>r.id===credit.settlementId),original=source&&s.orders.find(o=>o.id===source.orderId);
 const targets=s.orders.filter(o=>o.customerId===original?.customerId&&o.id!==original.id&&!['Returned','Cancelled'].includes(o.status)&&orderBalance(o)>0);
 async function submit(e:React.FormEvent){e.preventDefault();if(posting)return;setPosting(true);try{if(decision)await onAction('settlement',decision);else if(credit)await onAction('credit',credit,credit.orderId);setDecision(null);setCredit(null);toast.success('Return settlement saved.')}catch(e){toast.error(e instanceof Error?e.message:'Could not save settlement.')}finally{setPosting(false)}}
 return <>
 <section className="panel"><div className="panel-heading"><div><h2>Return settlement decisions</h2><p>Choose what the customer is owed before recording a payout. A decision does not move cash.</p></div><strong>{taka(customerCreditPayable(s))} customer credit</strong></div>
 <Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Decision</TableHead><TableHead>Amount</TableHead><TableHead>Reason</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{returns.map(o=>{const r=s.returnSettlements.find(r=>r.orderId===o.id);return <TableRow key={o.id}><TableCell>#{o.number}</TableCell><TableCell>{r?.kind||'Refund by default'}</TableCell><TableCell>{taka(r?.amount??customerPaidAmount(o))}</TableCell><TableCell>{r?.reason||'Decision not yet recorded'}</TableCell><TableCell>{canManage&&!r&&<button className="btn secondary small" disabled={busy||posting} onClick={()=>setDecision({id:uid(),orderId:o.id,date:today(),kind:'Refund',amount:customerPaidAmount(o),reason:''})}>Set settlement</button>}</TableCell></TableRow>})}</TableBody></Table>
 <p className="form-note">No refund requires a recorded agreement/reason. Store and exchange credit remain customer liabilities until applied to another order. Posted decisions are retained in the audit history.</p></section>
 <section className="panel"><div className="panel-heading"><h2>Available customer credits</h2></div>{s.returnSettlements.filter(r=>creditBalance(s,r)>0).map(r=>{const o=s.orders.find(o=>o.id===r.orderId)!;return <div className="close-action" key={r.id}><div><strong>#{o.number} · {r.kind} · {taka(creditBalance(s,r))}</strong><p>{s.customers.find(c=>c.id===o.customerId)?.name} · {r.reason}</p></div>{canManage&&<button className="btn secondary" disabled={busy||posting} onClick={()=>setCredit({id:uid(),settlementId:r.id,orderId:'',date:today(),amount:creditBalance(s,r)})}>Apply credit</button>}</div>})}{!s.returnSettlements.some(r=>creditBalance(s,r)>0)&&<p>No unused credits.</p>}
 {s.creditUses.length>0&&<div><h3>Credit application history</h3>{s.creditUses.map(u=><p key={u.id}>{u.date} · #{s.orders.find(o=>o.id===u.orderId)?.number} · {taka(u.amount)} applied</p>)}</div>}</section>
 <Dialog open={!!decision||!!credit} onOpenChange={v=>{if(!v&&!posting){setDecision(null);setCredit(null)}}}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>{decision?'Set return settlement':'Apply customer credit'}</DialogTitle><DialogDescription>{decision?'Record the agreed outcome. This does not pay the customer.':'Create the replacement order first, then apply its customer’s available credit.'}</DialogDescription></DialogHeader><form className="record-form" onSubmit={submit}>
 {decision&&<><label>Outcome<select aria-label="Settlement outcome" className="choice native-choice" disabled={posting} value={decision.kind} onChange={e=>{const kind=e.target.value as Settlement['kind'],o=s.orders.find(o=>o.id===decision.orderId)!;setDecision({...decision,id:uid(),kind,amount:kind==='No refund'?0:kind==='Refund'?customerPaidAmount(o):customerPaidAmount(o)-refundedAmount(s,o)})}}>{['Refund','No refund','Store credit','Exchange'].map(k=><option key={k}>{k}</option>)}</select></label>{decision.kind!=='No refund'&&<label>Agreed amount<Input aria-label="Settlement amount" type="number" min="0" step="0.01" required disabled={posting} value={decision.amount} onChange={e=>setDecision({...decision,id:uid(),amount:Number(e.target.value)})}/></label>}<label>Agreement / reason<textarea aria-label="Settlement reason" className="choice native-choice" required maxLength={2000} disabled={posting} value={decision.reason} onChange={e=>setDecision({...decision,id:uid(),reason:e.target.value})}/></label></>}
 {credit&&<><label>Replacement order<select aria-label="Replacement order" className="choice native-choice" value={credit.orderId} disabled={posting} required onChange={e=>{const o=targets.find(o=>o.id===e.target.value);setCredit({...credit,id:uid(),orderId:e.target.value,amount:o?Math.min(orderBalance(o),creditBalance(s,source!)):credit.amount})}}><option value="">Choose an order</option>{targets.map(o=><option key={o.id} value={o.id}>#{o.number} · {taka(orderBalance(o))} due</option>)}</select></label>{targets.length===0&&<p>No order with an outstanding balance exists for this customer. Create a replacement order first.</p>}<label>Credit amount<Input aria-label="Credit amount" type="number" min="0.01" step="0.01" required disabled={posting} value={credit.amount} onChange={e=>setCredit({...credit,id:uid(),amount:Number(e.target.value)})}/></label></>}
 <label>Date<Input aria-label="Settlement date" type="date" max={today()} required disabled={posting} value={decision?.date||credit?.date||today()} onChange={e=>{if(decision)setDecision({...decision,id:uid(),date:e.target.value});if(credit)setCredit({...credit,id:uid(),date:e.target.value})}}/></label><div className="form-actions"><button type="button" className="btn secondary" disabled={posting} onClick={()=>{setDecision(null);setCredit(null)}}>Cancel</button><button className="btn primary" disabled={busy||posting||!!credit&&!credit.orderId}>{posting?'Saving…':decision?'Save settlement':'Apply credit'}</button></div></form></DialogContent></Dialog>
 </>;
}
