'use client';
import React,{useEffect,useState} from 'react';
import { Users, Trash2 } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Choice } from './forms';

type Staff={email:string;role:'sales'|'inventory'|'viewer';joined:boolean;created:string};
const roleOptions=[{value:'sales',label:'Sales employee'},{value:'inventory',label:'Inventory manager'},{value:'viewer',label:'View only'}];
export default function Team({open,onClose}:{open:boolean;onClose:()=>void}){
  const [staff,setStaff]=useState<Staff[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState<'sales'|'inventory'|'viewer'>('sales'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false),[inviteLink,setInviteLink]=useState('');
  useEffect(()=>{if(!open)return;let active=true;setReady(false);setError('');fetch('/api/team',{cache:'no-store'}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error||'Could not load team.');if(active){setStaff(d.staff);setReady(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[open]);
  async function change(action:'save'|'remove'|'invite',targetEmail:string,nextRole=role){setBusy(true);setError('');setInviteLink('');try{const res=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email:targetEmail,role:nextRole})});const d:any=await res.json();if(!res.ok)throw Error(d.error||'Could not update team.');const updated=await fetch('/api/team',{cache:'no-store'});const list:any=await updated.json();if(!updated.ok)throw Error(list.error||'Could not refresh team.');setStaff(list.staff);if(d.inviteUrl)setInviteLink(d.inviteUrl);if(action==='save')setEmail('');}catch(e){setError(e instanceof Error?e.message:'Could not update team.')}finally{setBusy(false)}}
  return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="team-dialog"><DialogHeader><DialogTitle><Users size={20}/>Team access</DialogTitle><DialogDescription>Give each employee their own CRM account and role.</DialogDescription></DialogHeader>
    <div className="team-help"><strong>Invite staff</strong><p>Add their email and copy the one-time invitation link. Send it to them privately so they can set a password. The link expires after seven days.</p><p>Sales employees manage orders, customers and follow-ups. Inventory managers manage products, batches and suppliers. Only the owner manages finances, business settings and team access.</p></div>
    <form className="team-add" onSubmit={e=>{e.preventDefault();void change('save',email)}}><label>Email address<Input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="employee@example.com"/></label><label>CRM role<Choice value={role} onChange={v=>setRole(v as 'sales'|'inventory'|'viewer')} options={roleOptions}/></label><button className="btn primary" type="submit" disabled={busy}>Add person</button></form>
    <div className="team-list"><h3>People with CRM access</h3>{!ready&&!error&&<p className="muted">Loading team…</p>}{ready&&!staff.length&&<p className="muted">No one added yet. Your workspace is still yours alone.</p>}{staff.map(person=><div className="team-person" key={person.email}><div><strong>{person.email}</strong><small>{person.joined?'Password set':'Waiting for password setup'}</small></div><Choice value={person.role} onChange={v=>void change('save',person.email,v as 'sales'|'inventory'|'viewer')} options={roleOptions}/><button type="button" className="text-button" disabled={busy} onClick={()=>void change('invite',person.email)}>New link</button><button type="button" className="icon-button" aria-label={'Remove '+person.email} title="Remove access" disabled={busy} onClick={()=>void change('remove',person.email)}><Trash2 size={16}/></button></div>)}</div>
    {inviteLink&&<div className="invite-link"><label>Copy and privately share this one-time link<Input readOnly value={inviteLink} onFocus={e=>e.target.select()}/></label></div>}{error&&<p className="form-error" role="alert">{error}</p>}<p className="form-note">Removing an account revokes its active sessions immediately.</p>
  </DialogContent></Dialog>
}
