import { test,expect } from '@playwright/test';
const date=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function session(browser,role){const context=await browser.newContext({baseURL:'http://localhost:3100'}),request=context.request,fixture=await (await request.get('/api/e2e/fixture?role=viewer')).json(),origin=fixture.requestOrigin;const login=await request.post('/api/auth/login',{headers:{Origin:origin},data:{email:`e2e-${role}@aloyri.test`,password:process.env.E2E_PASSWORD||'Aloyri-E2E-Password-2026!'}});expect(login.status()).toBe(200);return {context,request,origin};}
test('return decisions, credit application, damage costs, history and paginated lists persist through authenticated workflows',async({browser})=>{
 test.setTimeout(180000);const owner=await session(browser,'owner'),post=(path,data)=>owner.request.post(path,{headers:{Origin:owner.origin},data});
 const inventory=await (await owner.request.get('/api/inventory-suppliers')).json();inventory.data.batches.push({id:'settlement-batch',productId:'simple-wash',qty:40,unitCost:500,received:date(),expiry:'2099-12-31',supplierId:'',invoice:'settlement-test',payments:[],paid:false});let r=await owner.request.put('/api/inventory-suppliers',{headers:{Origin:owner.origin},data:{data:inventory.data,domainVersion:inventory.domainVersion}});expect(r.status(),await r.text()).toBe(200);
 async function create(id,paidReturn=false){const order={id,number:id,customerId:'customer-1',created:date(),collections:[],channel:'Website',payment:'Bank',status:'New',items:[{productId:'simple-wash',qty:1,price:749,allocations:[{batchId:'settlement-batch',qty:1,unitCost:500}]}],discount:0,deliveryCharge:0,courierCost:0,packaging:0,paymentFee:0,returnFee:0,settled:false,restocked:false,tracking:'',notes:'Settlement regression'};r=await post('/api/orders',order);expect(r.status(),await r.text()).toBe(201);let saved=(await r.json()).order;if(!paidReturn)return saved;r=await post('/api/orders/'+id+'/collection',{recordVersion:saved.recordVersion,date:date(),amount:749,reference:'Original cash',account:'cash'});expect(r.status(),await r.text()).toBe(200);const c=await r.json();saved={...c.order,recordVersion:c.recordVersions[id]};for(const status of ['Confirmed','Ready to pack','Packed','Shipped','Out for delivery','Delivered','Returned']){r=await owner.request.put('/api/orders/'+id,{headers:{Origin:owner.origin},data:{order:{...saved,status,delivered:['Delivered','Returned'].includes(status)?date():undefined,returnedAt:status==='Returned'?date():undefined},recordVersion:saved.recordVersion}});expect(r.status(),await r.text()).toBe(200);saved=(await r.json()).order;}return saved;}
 await create('SETTLE-NO-REFUND',true);const creditSource=await create('SETTLE-CREDIT',true),replacement=await create('SETTLE-REPLACEMENT');
 const finance=await session(browser,'finance'),page=await finance.context.newPage();await page.goto('/');await expect(page.getByRole('heading',{name:'Work from collections, payables and account control.'})).toBeVisible({timeout:20000});await page.locator('.app-sidebar').getByRole('button',{name:'Finances',exact:true}).click();await page.getByRole('tab',{name:'Refunds',exact:true}).click();
 const decisions=page.locator('section').filter({has:page.getByRole('heading',{name:'Return settlement decisions',exact:true})}),noRefund=decisions.getByRole('row').filter({hasText:'#SETTLE-NO-REFUND'});
 await noRefund.getByRole('button',{name:'Set settlement'}).click();await page.getByLabel('Settlement outcome').selectOption('No refund');await page.getByLabel('Settlement reason').fill('Customer agreed to no refund');const save=page.waitForResponse(r=>r.url().endsWith('/api/finances/return-settlements')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save settlement',exact:true}).click();const saved=await save;expect(saved.status(),await saved.text()).toBe(200);await expect(page.getByRole('dialog')).toBeHidden({timeout:20000});await expect(noRefund).toContainText('No refund');
 const refunds=page.locator('section').filter({has:page.getByRole('heading',{name:'Customer refunds',exact:true})}).getByRole('row').filter({hasText:'#SETTLE-NO-REFUND'});await expect(refunds).toContainText('Settled without further refund');await expect(refunds.getByRole('button',{name:'Record refund'})).toHaveCount(0);
 let f=await (await owner.request.get('/api/finances')).json();const settlement={id:'store-credit-decision',orderId:creditSource.id,date:date(),kind:'Store credit',amount:749,reason:'Customer chose store credit'};r=await post('/api/finances/return-settlements',{settlement,domainVersion:f.domainVersion});expect(r.status(),await r.text()).toBe(200);
 const before=await (await owner.request.get('/api/workspace')).json();const credit={id:'credit-use-regression',settlementId:settlement.id,orderId:replacement.id,date:date(),amount:749};r=await post('/api/finances/customer-credit',{credit,recordVersion:replacement.recordVersion});expect(r.status(),await r.text()).toBe(200);r=await post('/api/finances/customer-credit',{credit,recordVersion:replacement.recordVersion});expect(r.status()).toBe(200);expect((await r.json()).duplicate).toBe(true);
 let after=await (await owner.request.get('/api/workspace')).json();expect(after.data.customerRefunds).toEqual(before.data.customerRefunds);expect(after.data.creditUses.filter(u=>u.id===credit.id)).toHaveLength(1);expect(after.data.orders.find(o=>o.id===replacement.id).collections[0].id).toBe('credit-'+credit.id);expect(after.data.accountMatches).toEqual(before.data.accountMatches);
 r=await post('/api/orders/'+creditSource.id+'/inspection',{recordVersion:creditSource.recordVersion,outcome:'Damaged'});expect(r.status(),await r.text()).toBe(200);after=await (await owner.request.get('/api/workspace')).json();expect(after.data.returnInspections.find(i=>i.orderId===creditSource.id).outcome).toBe('Damaged');expect(after.data.inventoryHolds.some(h=>h.sourceOrderId===creditSource.id&&h.type==='Damaged'&&!h.releasedAt)).toBe(true);
 f=await (await owner.request.get('/api/finances')).json();f.data.returnSettlements=[];r=await owner.request.put('/api/finances',{headers:{Origin:owner.origin},data:{data:f.data,domainVersion:f.domainVersion}});expect(r.status()).toBe(400);
 const first=await (await owner.request.get('/api/orders?page=1&pageSize=1&q=SETTLE-')).json(),second=await (await owner.request.get('/api/orders?page=2&pageSize=1&q=SETTLE-')).json();expect(first.orders).toHaveLength(1);expect(second.orders).toHaveLength(1);expect(first.orders[0].id).not.toBe(second.orders[0].id);expect(first.pagination.total).toBe(3);expect((await owner.request.get('/api/orders?pageSize=999')).status()).toBe(400);expect((await (await owner.request.get('/api/customers?page=1&pageSize=1')).json()).customers).toHaveLength(1);
 await page.reload();await expect(page.getByRole('heading',{name:'Work from collections, payables and account control.'})).toBeVisible({timeout:20000});await page.locator('.app-sidebar').getByRole('button',{name:'Finances',exact:true}).click();await page.getByRole('tab',{name:'Refunds',exact:true}).click();await expect(noRefund).toContainText('No refund');
 for(const role of ['sales','inventory','viewer']){const denied=await session(browser,role);r=await denied.request.post('/api/finances/return-settlements',{headers:{Origin:denied.origin},data:{settlement,domainVersion:0}});expect(r.status()).toBe(403);r=await denied.request.get('/api/workspace/automatic-backups');expect(r.status()).toBe(403);await denied.context.close();}
 const backups=await (await owner.request.get('/api/workspace/automatic-backups')).json();expect(backups.backups.length).toBeGreaterThan(0);r=await owner.request.get('/api/workspace/automatic-backups?day='+String(backups.backups[0].day).slice(0,10));expect(r.status(),await r.text()).toBe(200);const backup=await r.json();r=await post('/api/workspace/backup',{action:'validate',backup});expect(r.status(),await r.text()).toBe(200);
 await finance.context.close();await owner.context.close();
});
test('recovery codes require password confirmation, work once and revoke prior sessions',async({browser})=>{
 const staff=await session(browser,'inventory'),headers={Origin:staff.origin},password=process.env.E2E_PASSWORD||'Aloyri-E2E-Password-2026!';let r=await staff.request.post('/api/auth/recovery-codes',{headers,data:{current:'wrong-password'}});expect(r.status()).toBe(403);r=await staff.request.post('/api/auth/recovery-codes',{headers,data:{current:password}});expect(r.status(),await r.text()).toBe(200);const {codes}=await r.json();expect(codes).toHaveLength(8);
 const context=await browser.newContext({baseURL:'http://localhost:3100'}),page=await context.newPage();await page.goto('/login');await page.getByRole('link',{name:'Forgot password?'}).click();await expect(page.getByRole('heading',{name:'Recover your account'})).toBeVisible();await page.getByLabel('Recovery email').fill('e2e-inventory@aloyri.test');await page.getByLabel('Recovery code',{exact:true}).fill(codes[0]);await page.getByLabel('Recovery new password').fill(password);await page.getByLabel('Confirm recovery password').fill(password);await page.getByRole('button',{name:'Reset password'}).click();await expect(page.getByText('Password updated.',{exact:false})).toBeVisible({timeout:20000});expect((await staff.request.get('/api/workspace')).status()).toBe(401);
 r=await context.request.post('/api/auth/recover',{headers,data:{email:'e2e-inventory@aloyri.test',code:codes[0],password}});expect(r.status()).toBe(400);r=await context.request.post('/api/auth/login',{headers,data:{email:'e2e-inventory@aloyri.test',password}});expect(r.status()).toBe(200);expect((await (await context.request.get('/api/auth/recovery-codes')).json()).remaining).toBe(7);await context.close();await staff.context.close();
});
