import { test,expect } from '@playwright/test';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function login(browser,role){const context=await browser.newContext({baseURL:'http://localhost:3100'}),request=context.request,fixture=await (await request.get('/api/e2e/fixture?role=viewer')).json(),origin=fixture.requestOrigin;const r=await request.post('/api/auth/login',{headers:{Origin:origin},data:{email:`e2e-${role}@aloyri.test`,password:process.env.E2E_PASSWORD||'Aloyri-E2E-Password-2026!'}});expect(r.status()).toBe(200);return {context,request,origin};}
test('server pages, cross-page selections, history, search, reports and full CSV export use complete records',async({browser})=>{
 test.setTimeout(300000);const owner=await login(browser,'owner'),post=(path,data)=>owner.request.post(path,{headers:{Origin:owner.origin},data});
 const inventory=await (await owner.request.get('/api/inventory-suppliers')).json();inventory.data.batches.push({id:'page-batch',productId:'simple-wash',qty:100,unitCost:500,received:today(),expiry:'2099-12-31',supplierId:'',invoice:'PAGE-STOCK',payments:[],paid:false});let r=await owner.request.put('/api/inventory-suppliers',{headers:{Origin:owner.origin},data:{data:inventory.data,domainVersion:inventory.domainVersion}});expect(r.status(),await r.text()).toBe(200);
 for(let i=0;i<31;i++){const suffix=String(i).padStart(3,'0');r=await post('/api/customers',{id:'page-c-'+suffix,name:'PAGE Customer '+suffix,phone:'',address:'Address',city:'Dhaka',preference:'',notes:'',consent:true,created:today()});expect(r.status(),await r.text()).toBe(201);r=await post('/api/orders',{id:'page-o-'+suffix,number:'PAGE-ORDER-'+suffix,customerId:'page-c-000',created:today(),collections:[],channel:'Website',payment:'Bank',status:'New',items:[{productId:'simple-wash',qty:1,price:749,allocations:[{batchId:'page-batch',qty:1,unitCost:500}]}],discount:0,deliveryCharge:0,courierCost:0,packaging:0,paymentFee:0,returnFee:0,settled:false,restocked:false,tracking:'',notes:''});expect(r.status(),await r.text()).toBe(201);}
 const compact=await (await owner.request.get('/api/workspace?compact=1')).json();expect(compact.compact).toBe(true);expect(compact.data.orders.length).toBeLessThanOrEqual(5);expect(compact.data.customers.length).toBeLessThanOrEqual(5);expect(compact.summary.overview.customerCount).toBeGreaterThanOrEqual(31);expect(Array.isArray(compact.summary.report.reportOrders)).toBe(false);
 r=await owner.request.get('/api/orders');const defaultPage=await r.json();expect(defaultPage.orders.length).toBeLessThanOrEqual(25);expect(defaultPage.pagination.pageSize).toBe(25);
 const page=await owner.context.newPage(),reads=[];page.on('request',r=>{if(r.method()==='GET')reads.push(new URL(r.url()).pathname+new URL(r.url()).search)});await page.goto('/');await expect(page.getByRole('heading',{name:'Run the business from what needs attention now.'})).toBeVisible({timeout:30000});
 await page.locator('.app-sidebar').getByRole('button',{name:'Orders',exact:true}).click();await page.getByRole('textbox',{name:'Search orders'}).fill('PAGE-ORDER-');const table=page.locator('.orders-desktop-table');await expect(page.getByRole('navigation',{name:'Record pages'})).toContainText('1–25 of 31',{timeout:30000});await expect(table.getByRole('row')).toHaveCount(26);
 await table.getByRole('checkbox',{name:'Select order PAGE-ORDER-000',exact:true}).check();await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(page.getByRole('navigation',{name:'Record pages'})).toContainText('26–31 of 31');await expect(table.getByRole('row')).toHaveCount(7);await table.getByRole('checkbox',{name:'Select order PAGE-ORDER-025',exact:true}).check();await expect(page.locator('.bulk-action-bar')).toContainText('2 orders selected');await page.getByRole('button',{name:'Advance one step'}).click();await page.getByRole('button',{name:'Advance orders',exact:true}).click();await expect(page.locator('.bulk-action-bar')).toHaveCount(0,{timeout:30000});for(const id of ['page-o-000','page-o-025'])expect((await (await owner.request.get('/api/orders/'+id)).json()).order.status).toBe('Confirmed');
 await page.locator('.app-sidebar').getByRole('button',{name:'Customers',exact:true}).click();await page.getByRole('textbox',{name:'Search customers'}).fill('PAGE Customer');await expect(page.getByRole('navigation',{name:'Record pages'})).toContainText('1–25 of 31');const customerRow=page.locator('.customers-desktop').getByRole('row').filter({hasText:'PAGE Customer 000'});await expect(customerRow).toContainText('31');await customerRow.getByRole('button',{name:'Open PAGE Customer 000',exact:true}).click();await expect(page.getByRole('heading',{name:'Purchase history',exact:true})).toBeVisible();const history=page.getByRole('dialog');await expect(history.getByRole('navigation',{name:'Record pages'})).toContainText('1–25 of 31');await history.getByRole('button',{name:'Next page',exact:true}).click();await expect(history.getByRole('navigation',{name:'Record pages'})).toContainText('26–31 of 31');await page.keyboard.press('Escape');
 await page.getByRole('combobox',{name:'Search the CRM'}).fill('PAGE-ORDER-030');await page.getByRole('option').filter({hasText:'#PAGE-ORDER-030'}).click();await expect(page.getByRole('dialog')).toContainText('PAGE-ORDER-030');await page.keyboard.press('Escape');
 await page.locator('.app-sidebar').getByRole('button',{name:'Reports',exact:true}).click();await expect(page.getByRole('heading',{name:'Executive performance overview'})).toBeVisible();expect(reads.filter(url=>url==='/api/workspace'||url.includes('versions=1'))).toEqual([]);expect(reads.filter(url=>url==='/api/orders'||url==='/api/customers')).toEqual([]);
 r=await owner.request.get('/api/orders/export');expect(r.status(),await r.text()).toBe(200);const csv=await r.text();expect(csv).toContain('PAGE-ORDER-000');expect(csv).toContain('PAGE-ORDER-030');expect(csv.split('\r\n').filter(l=>l.includes('PAGE-ORDER-'))).toHaveLength(31);
 r=await owner.request.get('/api/customers?page=1&pageSize=1&q=PAGE%20Customer%20000');const stats=await r.json();expect(stats.orderStats['page-c-000'].orders).toBe(31);expect(stats.orderStats['page-c-000'].deliveredSpend).toBe(0);r=await owner.request.get('/api/orders?page=1&q=%25');expect((await r.json()).pagination.total).toBe(0);
 for(const role of ['sales','inventory','finance','viewer']){const staff=await login(browser,role);const s=await (await staff.request.get('/api/workspace?compact=1')).json();expect(s.summary.report).toBeUndefined();if(role==='inventory')expect((await staff.request.get('/api/orders?page=1')).status()).toBe(403);if(role==='sales'){const o=await (await staff.request.get('/api/orders?page=1&q=PAGE-ORDER-')).json();expect(o.orders.every(x=>x.items.every(i=>i.allocations.every(a=>a.unitCost===0)))).toBe(true);expect((await staff.request.get('/api/orders/export')).status()).toBe(403);}if(['finance','viewer','inventory'].includes(role))expect((await staff.request.post('/api/customers/bulk-follow-ups',{headers:{Origin:staff.origin},data:{ids:['page-c-001'],version:s.version}})).status()).toBe(403);await staff.context.close();}
 await owner.context.close();
});
