import { test,expect } from '@playwright/test';
const date=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function session(browser,role){const context=await browser.newContext({baseURL:'http://localhost:3100'}),fixture=await (await context.request.get('/api/e2e/fixture?role=viewer')).json(),origin=fixture.requestOrigin;expect((await context.request.post('/api/auth/login',{headers:{Origin:origin},data:{email:`e2e-${role}@aloyri.test`,password:process.env.E2E_PASSWORD||'Aloyri-E2E-Password-2026!'}})).status()).toBe(200);return {context,request:context.request,origin};}
test('all CRM operating lists use server pages, complete totals, safe cross-page actions and role restrictions',async({browser})=>{
 test.setTimeout(300000);const owner=await session(browser,'owner'),put=(path,data)=>owner.request.put(path,{headers:{Origin:owner.origin},data});
 const inventory=await (await owner.request.get('/api/inventory-suppliers')).json(),template=inventory.data.products[0];
 for(let i=0;i<31;i++){const n=String(i).padStart(3,'0'),productId='section-product-'+n,supplierId='section-supplier-'+n,batchId='section-batch-'+n;inventory.data.products.push({...template,id:productId,name:'SECTION Product '+n,active:true,reorderAt:20});inventory.data.suppliers.push({id:supplierId,name:'SECTION Supplier '+n,contact:'',phone:'',email:'',address:'',leadDays:14,paymentTermsDays:30,notes:'',verified:false});inventory.data.batches.push({id:batchId,productId,qty:10,unitCost:10,received:date(),expiry:'2099-12-31',supplierId,invoice:'SECTION-BATCH-'+n,payments:[],paid:false});inventory.data.purchaseOrders.push({id:'section-po-'+n,number:'SECTION-PO-'+n,supplierId,created:date(),expected:date(),status:'Draft',notes:'',items:[{productId,qty:10,unitCost:10,receivedQty:0}]});inventory.data.inventoryHolds.push({id:'section-hold-'+n,batchId,qty:1,type:'Damaged',source:'Manual',date:date(),reason:'SECTION inspection'});}
 let r=await put('/api/inventory-suppliers',{data:inventory.data,domainVersion:inventory.domainVersion});expect(r.status(),await r.text()).toBe(200);
 const finances=await (await owner.request.get('/api/finances')).json();if(!finances.data.accountOpenings.some(a=>a.account==='cash'))finances.data.accountOpenings.push({account:'cash',date:date(),balance:1000});
 for(let i=0;i<31;i++){const n=String(i).padStart(3,'0');finances.data.expenses.push({id:'section-expense-'+n,date:date(),category:'Advertising',amount:1,notes:'SECTION Expense '+n,vendor:'',reference:'',recurring:'none'});finances.data.cashEntries.push({id:'section-cash-'+n,date:date(),kind:'in',category:'Other',description:'SECTION Cash '+n,amount:1});finances.data.accountMatches.push({entryId:'manual-section-cash-'+n,account:'cash',matched:false,reference:''});}
 r=await put('/api/finances',{data:finances.data,domainVersion:finances.domainVersion});expect(r.status(),await r.text()).toBe(200);
 let workspace=await (await owner.request.get('/api/workspace')).json();const tasks=[...workspace.data.tasks];for(let i=0;i<31;i++){const n=String(i).padStart(3,'0');tasks.push({id:'section-task-'+n,customerId:'customer-1',orderId:'',title:'SECTION Task '+n,due:date(),done:false,kind:'Follow-up',priority:'High',channel:'WhatsApp',notes:'',completedAt:''});}
 r=await put('/api/workspace/preferences',{patch:{tasks},version:workspace.version});expect(r.status(),await r.text()).toBe(200);workspace=await (await owner.request.get('/api/workspace')).json();
 const before=await (await owner.request.get('/api/finances')).json(),page=await owner.context.newPage();await page.goto('/');await expect(page.getByRole('heading',{name:'Run the business from what needs attention now.'})).toBeVisible();
 const nav=name=>page.locator('.app-sidebar').getByRole('button',{name,exact:true}),pages=scope=>scope.getByRole('navigation',{name:'Record pages'});
 await nav('Inventory').click();await page.getByLabel('Search inventory').fill('SECTION Product');await expect(pages(page)).toContainText('1–25 of 31');await expect(page.locator('.inventory-products-desktop').getByRole('row')).toHaveCount(26);await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(page)).toContainText('26–31 of 31');await expect(page.locator('.inventory-products-desktop')).toContainText('SECTION Product 030');
 await page.getByRole('tab',{name:'Batches',exact:true}).click();await page.getByLabel('Search inventory').fill('SECTION-BATCH');await expect(pages(page)).toContainText('1–25 of 31');await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(page)).toContainText('26–31 of 31');
 await nav('Suppliers').click();await page.getByLabel('Search purchase orders').fill('SECTION-PO');await expect(pages(page)).toContainText('1–25 of 31');const pipeline=page.locator('.purchasing-desktop-table');await pipeline.getByRole('checkbox',{name:'Select purchase order SECTION-PO-000',exact:true}).check();await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(page)).toContainText('26–31 of 31');await pipeline.getByRole('checkbox',{name:'Select purchase order SECTION-PO-030',exact:true}).check();await page.getByRole('button',{name:'Mark drafts sent',exact:true}).click();await page.getByRole('button',{name:'Mark sent',exact:true}).click();await expect(page.locator('.bulk-action-bar')).toHaveCount(0,{timeout:20000});let savedInventory=await (await owner.request.get('/api/inventory-suppliers')).json();for(const id of ['section-po-000','section-po-030'])expect(savedInventory.data.purchaseOrders.find(p=>p.id===id).status).toBe('Sent');
 await page.getByRole('tab',{name:'Supplier directory',exact:true}).click();await page.getByLabel('Search suppliers').fill('SECTION Supplier');await expect(pages(page)).toContainText('1–25 of 31');await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(page)).toContainText('26–31 of 31');
 await nav('Follow-ups').click();await page.getByLabel('Search follow-ups').fill('SECTION Task');await expect(pages(page)).toContainText('1–25 of 31');await page.getByRole('checkbox',{name:'Select SECTION Task 000',exact:true}).check();await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(page)).toContainText('26–31 of 31');await page.getByRole('checkbox',{name:'Select SECTION Task 030',exact:true}).check();await page.getByRole('button',{name:'Mark complete',exact:true}).click();await page.getByRole('button',{name:'Complete follow-ups',exact:true}).click();await expect(page.locator('.bulk-action-bar')).toHaveCount(0,{timeout:20000});workspace=await (await owner.request.get('/api/workspace')).json();for(const id of ['section-task-000','section-task-030'])expect(workspace.data.tasks.find(t=>t.id===id).done).toBe(true);
 await nav('Finances').click();await page.getByRole('tab',{name:'Expenses',exact:true}).click();const expenses=page.locator('section').filter({has:page.getByRole('heading',{name:'Expense management',exact:true})});await expect(expenses.getByRole('row')).toHaveCount(26);await expenses.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(expenses)).toContainText('Page 2');
 await page.getByRole('tab',{name:'Cashflow',exact:true}).click();const cashPanel=page.locator('section').filter({has:page.getByRole('columnheader',{name:'Cash in',exact:true})});await expect(cashPanel.getByRole('row')).toHaveCount(26);await cashPanel.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(cashPanel)).toContainText('Page 2');
 await page.getByRole('tab',{name:'Payables',exact:true}).click();const payables=page.locator('section').filter({has:page.getByRole('heading',{name:'Supplier payables',exact:true})});await expect(payables.getByRole('row')).toHaveCount(26);await payables.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(payables)).toContainText('Page 2');
 await nav('Activity').click();await expect(page.locator('.activity-desktop').getByRole('row')).toHaveCount(26);await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(pages(page)).toContainText('Page 2');await page.getByLabel('Search activity history').fill('PAGE Customer 000');await expect(pages(page)).toContainText('1–1 of 1');await expect(page.locator('.activity-desktop')).toContainText('Created customer PAGE Customer 000');
 r=await owner.request.get('/api/audit?page=1&pageSize=25&section=tasks');const audit=await r.json();expect(r.status()).toBe(200);expect(audit.events.every(e=>e.sections.includes('tasks'))).toBe(true);expect(audit.pagination.total).toBeGreaterThan(0);
 const after=await (await owner.request.get('/api/finances')).json();expect(after.data).toEqual(before.data);
 r=await owner.request.get('/api/record-pages?kind=expenses&page=1&pageSize=201');expect(r.status()).toBe(400);r=await owner.request.get('/api/record-pages?kind=assigned&account=foreign');expect(r.status()).toBe(400);r=await owner.request.get('/api/record-pages?kind=expenses&expectedVersion=0');expect(r.status()).toBe(409);
 for(const role of ['sales','inventory','finance','viewer']){const staff=await session(browser,role);const expenseResult=await staff.request.get('/api/record-pages?kind=expenses&page=1');expect(expenseResult.status()).toBe(['finance','viewer'].includes(role)?200:403);const taskResult=await staff.request.get('/api/record-pages?kind=tasks&page=1');expect(taskResult.status()).toBe(['sales','viewer'].includes(role)?200:403);expect((await staff.request.get('/api/record-pages?kind=automation&page=1')).status()).toBe(403);expect((await staff.request.get('/api/audit?page=1')).status()).toBe(403);await staff.context.close();}
 await owner.context.close();
});
