import { z } from 'zod';
export const statuses = ['New','Confirmed','Packed','Shipped','Delivered','Returned','Cancelled'] as const;
export const categories = ['Cleanser','Moisturizer','Sunscreen','Lip care','Other'] as const;
export const channels = ['Facebook','Instagram','WhatsApp','Website','Other'] as const;
export const expenseCategories = ['Advertising','Content','Tools','Packaging','Registration','Courier & returns','Other'] as const;
export const accountIds = ['cash','bank','bkash','nagad'] as const;
export const accountNames:Record<typeof accountIds[number],string>={cash:'Cash',bank:'Bank',bkash:'bKash',nagad:'Nagad'};
const str = z.string().trim().max(2000), id = z.string().min(1).max(100);
const money = z.number().finite().min(0).max(10000000), qty = z.number().int().min(1).max(100000);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0,10)===v);
export const productSchema = z.object({id,name:str.min(1),brand:str,size:str,category:z.string().trim().min(1).max(50),price:money,cost:money,targetQty:z.number().int().min(0).max(100000),reorderAt:z.number().int().min(0).max(100000),active:z.boolean()});
const customerSchema = z.object({id,name:str.min(1),phone:str,address:str,city:str,preference:str,notes:str,consent:z.boolean(),created:date});
const supplierSchema = z.object({id,name:str.min(1),contact:str,phone:str,notes:str,verified:z.boolean()});
const purchasePaymentSchema=z.object({id,date,amount:money.refine(n=>n>0),note:str.default('')});
const batchSchema = z.object({id,productId:id,qty,unitCost:money,expiry:date,received:date,supplierId:str,invoice:str,dueDate:date.optional(),payments:z.array(purchasePaymentSchema).max(100).default([]),paid:z.boolean(),paidAt:date.optional()});
const stockAdjustmentSchema = z.object({id,batchId:id,delta:z.number().int().min(-100000).max(100000).refine(v=>v!==0),date,reason:str.min(1)});
const allocationSchema = z.object({batchId:id,qty,unitCost:money});
const collectionSchema=z.object({id,date,amount:money.refine(n=>n>0),reference:str.default('')});
const orderSchema = z.object({id,number:str,customerId:id,created:date,delivered:date.optional(),settledAt:date.optional(),collections:z.array(collectionSchema).max(100).default([]),channel:z.enum(channels),payment:z.enum(['COD','bKash','Nagad','Bank']),status:z.enum(statuses),items:z.array(z.object({productId:id,qty,price:money,allocations:z.array(allocationSchema).min(1)})).min(1).max(50),discount:money,deliveryCharge:money,courierCost:money,packaging:money,paymentFee:money,returnFee:money,settled:z.boolean(),restocked:z.boolean(),tracking:str,notes:str});
const expenseSchema = z.object({id,category:z.enum(expenseCategories),amount:money,date,notes:str});
const cashEntrySchema = z.object({id,date,kind:z.enum(['in','out']),category:z.string().trim().min(1).max(100),description:str,amount:money.refine(n=>n>0),transferId:id.optional()});
const accountOpeningSchema=z.object({account:z.enum(accountIds),date,balance:money,statementDate:date.optional(),statementBalance:money.optional()});
const accountMatchSchema=z.object({entryId:id,account:z.enum(accountIds),matched:z.boolean(),reference:z.string().trim().max(200)});
const businessProfileSchema=z.object({phone:z.string().trim().max(40),email:z.union([z.literal(''),z.string().trim().email().max(200)]),address:z.string().trim().max(500),bin:z.string().trim().max(60),logoDataUrl:z.union([z.literal(''),z.string().regex(/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/).max(150000)]),invoiceFooter:z.string().trim().max(500),returnPolicy:z.string().trim().max(500)});
export const emptyBusinessProfile=()=>({phone:'',email:'',address:'',bin:'',logoDataUrl:'',invoiceFooter:'',returnPolicy:''});
const taskSchema = z.object({id,customerId:str,title:str.min(1),due:date,done:z.boolean(),kind:z.enum(['Follow-up','Replenishment','Other'])});
export const stateSchema = z.object({products:z.array(productSchema).max(2000),productCategories:z.array(z.string().trim().min(1).max(50)).min(1).max(100).default(()=>[...categories]),customers:z.array(customerSchema).max(10000),suppliers:z.array(supplierSchema).max(1000),batches:z.array(batchSchema).max(10000),stockAdjustments:z.array(stockAdjustmentSchema).max(10000).default([]),orders:z.array(orderSchema).max(10000),expenses:z.array(expenseSchema).max(10000),cashEntries:z.array(cashEntrySchema).max(10000).default([]),accountOpenings:z.array(accountOpeningSchema).max(4).default([]),accountMatches:z.array(accountMatchSchema).max(30000).default([]),tasks:z.array(taskSchema).max(10000),budget:money,businessName:str.min(1),businessProfile:businessProfileSchema.default(emptyBusinessProfile)});
export type State=z.infer<typeof stateSchema>;
export type Product=State['products'][number]; export type Customer=State['customers'][number]; export type Order=State['orders'][number]; export type Batch=State['batches'][number];
export type Supplier=State['suppliers'][number]; export type Task=State['tasks'][number];
export const uid=()=>{if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const shiftDate=(days:number,base=today())=>{const d=new Date(base+'T12:00:00Z'); d.setUTCDate(d.getUTCDate()+days); return d.toISOString().slice(0,10)};
export const taka=(n:number)=>'৳'+Math.round(n).toLocaleString('en-BD');
export const dateLabel=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
export function initialState():State {return {businessName:'ALOYRI',businessProfile:emptyBusinessProfile(),budget:120000,productCategories:[...categories],customers:[],suppliers:[],batches:[],stockAdjustments:[],orders:[],expenses:[],cashEntries:[],accountOpenings:[],accountMatches:[],tasks:[],products:[
  {id:'simple-wash',brand:'Simple',name:'Refreshing Facial Wash',size:'150ml · Poland',category:'Cleanser',price:749,cost:520,targetQty:12,reorderAt:4,active:true},
  {id:'simple-light',brand:'Simple',name:'Hydrating Light Moisturiser',size:'125ml · Hungary',category:'Moisturizer',price:749,cost:520,targetQty:10,reorderAt:4,active:true},
  {id:'simple-rich',brand:'Simple',name:'Replenishing Rich Moisturizer',size:'125ml',category:'Moisturizer',price:775,cost:540,targetQty:6,reorderAt:3,active:true},
  {id:'skin-cafe',brand:'Skin Cafe',name:'Lightweight Sunscreen SPF50 PA+++',size:'60g',category:'Sunscreen',price:549,cost:380,targetQty:12,reorderAt:4,active:true},
  {id:'skin-aqua',brand:'Rohto',name:'Skin Aqua Super Moisture UV Gel',size:'110g · SPF50+ PA++++',category:'Sunscreen',price:1350,cost:940,targetQty:6,reorderAt:3,active:true},
  {id:'cosrx',brand:'COSRX',name:'Low pH Good Morning Gel Cleanser',size:'50ml',category:'Cleanser',price:580,cost:400,targetQty:6,reorderAt:3,active:true}
]};}
export function usedByBatch(s:State,batchId:string) {return s.orders.filter(o=>o.status!=='Cancelled' && !(o.status==='Returned'&&o.restocked)).flatMap(o=>o.items.flatMap(i=>i.allocations)).filter(a=>a.batchId===batchId).reduce((n,a)=>n+a.qty,0)}
export const batchRemaining=(s:State,b:Batch)=>b.qty+(s.stockAdjustments||[]).filter(a=>a.batchId===b.id).reduce((n,a)=>n+a.delta,0)-usedByBatch(s,b.id);
export const stock=(s:State,id:string)=>s.batches.filter(b=>b.productId===id&&b.expiry>today()).reduce((n,b)=>n+batchRemaining(s,b),0);
export const subtotal=(o:Order)=>o.items.reduce((n,i)=>n+i.price*i.qty,0)-o.discount;
export const total=(o:Order)=>subtotal(o)+o.deliveryCharge;
export const costOfOrder=(o:Order)=>o.items.flatMap(i=>i.allocations).reduce((n,a)=>n+a.unitCost*a.qty,0);
export const contribution=(o:Order)=>subtotal(o)-costOfOrder(o)+o.deliveryCharge-o.courierCost-o.packaging-o.paymentFee;
export function allocate(s:State,productId:string,quantity:number) {let remaining=quantity;const result:{batchId:string;qty:number;unitCost:number}[]=[];for(const b of s.batches.filter(b=>b.productId===productId&&b.expiry>today()).sort((a,b)=>a.expiry.localeCompare(b.expiry))){const amount=Math.min(remaining,batchRemaining(s,b));if(amount>0){result.push({batchId:b.id,qty:amount,unitCost:b.unitCost});remaining-=amount;}if(!remaining)break;}if(remaining)throw new Error('Not enough unexpired stock. Receive stock first.');return result;}
export function nextStatuses(o:Order):Order['status'][] {return ({New:['Confirmed','Cancelled'],Confirmed:['Packed','Cancelled'],Packed:['Shipped','Cancelled'],Shipped:['Delivered','Returned'],Delivered:[],Returned:[],Cancelled:[]} as Record<string,Order['status'][]>)[o.status];}
export function validateRelations(s:State) {
  if(new Set(s.productCategories.map(c=>c.toLowerCase())).size!==s.productCategories.length)throw new Error('Product categories must have unique names.');
  for(const p of s.products)if(!s.productCategories.includes(p.category))throw new Error('A product uses a category that is missing from Inventory.');
  for(const list of [s.products,s.customers,s.suppliers,s.batches,s.stockAdjustments,s.orders,s.expenses,s.cashEntries,s.tasks])if(new Set(list.map(x=>x.id)).size!==list.length)throw new Error('Duplicate record identifiers.');
  if(new Set(s.accountOpenings.map(a=>a.account)).size!==s.accountOpenings.length)throw new Error('Each account needs one opening balance.');
  if(new Set(s.accountMatches.map(m=>m.entryId)).size!==s.accountMatches.length)throw new Error('A cash movement can only be assigned to one account.');
  const movementDates=new Map(cashflow(s).entries.map(e=>[e.id,e.date]));
  for(const a of s.accountOpenings)if(a.date>today()||a.statementDate&&(a.statementDate<a.date||a.statementDate>today()))throw new Error('Check the account opening and statement dates.');
  for(const m of s.accountMatches){const opening=s.accountOpenings.find(a=>a.account===m.account),movementDate=movementDates.get(m.entryId);if(!opening||!movementDate||movementDate<opening.date)throw new Error('An account assignment needs a movement on or after its opening date.');}
  for(const b of s.batches){const amount=b.qty*b.unitCost,paidAmount=b.payments.reduce((n,p)=>n+p.amount,0);if(paidAmount>amount+.001)throw new Error('Supplier payments cannot exceed the purchase amount.');if(b.dueDate&&b.dueDate<b.received)throw new Error('Supplier due date cannot be before the stock receipt date.');for(const p of b.payments)if(p.date>today())throw new Error('Supplier payment date cannot be in the future.');if(b.paidAt&&!b.paid)throw new Error('Unpaid stock cannot have a payment date.');}
  for(const o of s.orders){const due=Math.max(0,total(o)-o.courierCost-o.paymentFee),collected=o.collections.reduce((n,p)=>n+p.amount,0);if(collected>due+.001)throw new Error('Order collections cannot exceed the net receivable.');for(const p of o.collections)if(p.date>today())throw new Error('Collection date cannot be in the future.');if(o.settledAt&&!o.settled)throw new Error('Unsettled orders cannot have a payment date.');}
  for(const a of s.stockAdjustments)if(!s.batches.some(b=>b.id===a.batchId))throw new Error('Stock adjustment refers to an unknown batch.');
  for(const b of s.batches){if(!s.products.some(p=>p.id===b.productId))throw new Error('Unknown product.');if(b.expiry<=b.received)throw new Error('Expiry must be after receipt.');if(b.supplierId&&!s.suppliers.some(p=>p.id===b.supplierId))throw new Error('Unknown supplier.');if(batchRemaining(s,b)<0)throw new Error('Stock is over-allocated.');}
  for(const o of s.orders){if(!s.customers.some(c=>c.id===o.customerId))throw new Error('Select a customer.');if(subtotal(o)<0)throw new Error('Discount exceeds the product total.');if(o.status==='Delivered'&&!o.delivered)throw new Error('Delivery date is required.');if(o.settled&&o.status!=='Delivered')throw new Error('Only delivered orders can be settled.');for(const i of o.items){if(!s.products.some(p=>p.id===i.productId))throw new Error('Unknown product.');if(i.allocations.reduce((n,a)=>n+a.qty,0)!==i.qty)throw new Error('Invalid stock allocation.');for(const a of i.allocations){const b=s.batches.find(b=>b.id===a.batchId);if(!b||b.productId!==i.productId||b.unitCost!==a.unitCost)throw new Error('Invalid batch allocation.');}}}
  for(const t of s.tasks)if(t.customerId&&!s.customers.some(c=>c.id===t.customerId))throw new Error('Unknown follow-up customer.');
}
export function metrics(s:State) {const delivered=s.orders.filter(o=>o.status==='Delivered');const returned=s.orders.filter(o=>o.status==='Returned');const sales=delivered.reduce((n,o)=>n+subtotal(o),0);const costs=s.expenses.reduce((n,e)=>n+e.amount,0);const profit=delivered.reduce((n,o)=>n+contribution(o),0)-returned.reduce((n,o)=>n+o.courierCost+o.returnFee+o.packaging+o.paymentFee,0)-costs;return {sales,profit,expenses:costs,delivered:delivered.length,open:s.orders.filter(o=>!['Delivered','Returned','Cancelled'].includes(o.status)).length,pending:delivered.reduce((n,o)=>{const due=Math.max(0,total(o)-o.courierCost-o.paymentFee),legacy=o.settled&&o.collections.length===0?due:0;return n+Math.max(0,due-o.collections.reduce((x,p)=>x+p.amount,0)-legacy)},0),stockValue:s.batches.reduce((n,b)=>n+batchRemaining(s,b)*b.unitCost,0),stockPurchases:s.batches.reduce((n,b)=>n+b.qty*b.unitCost,0),unpaidStock:s.batches.reduce((n,b)=>n+Math.max(0,b.qty*b.unitCost-b.payments.reduce((x,p)=>x+p.amount,0)-(b.paid&&b.payments.length===0?b.qty*b.unitCost:0)),0)};}
export const accountBalance=(s:State,account:typeof accountIds[number])=>{const opening=s.accountOpenings.find(a=>a.account===account);if(!opening)return null;const links=new Map(s.accountMatches.map(m=>[m.entryId,m]));return opening.balance+cashflow(s).entries.filter(e=>e.date>=opening.date&&links.get(e.id)?.account===account).reduce((n,e)=>n+(e.kind==='in'?e.amount:-e.amount),0)};
export function cashflow(s:State){
  const entries:{id:string;date:string;kind:'in'|'out';source:string;description:string;amount:number}[]=[];
  for(const o of s.orders.filter(o=>o.status==='Delivered')){const payout=Math.max(0,total(o)-o.courierCost-o.paymentFee);if(o.collections.length)for(const p of o.collections)entries.push({id:'order-collection-'+o.id+'-'+p.id,date:p.date,kind:'in',source:'Order collection',description:'#'+o.number+(p.reference?' · '+p.reference:''),amount:p.amount});else if(o.settled&&o.settledAt&&payout)entries.push({id:'order-'+o.id,date:o.settledAt,kind:'in',source:'Order settlement',description:'#'+o.number,amount:payout});}
  for(const b of s.batches){const description=b.invoice||s.products.find(p=>p.id===b.productId)?.name||'Stock';if(b.payments.length)for(const p of b.payments)entries.push({id:'batch-payment-'+b.id+'-'+p.id,date:p.date,kind:'out',source:'Stock purchase',description,amount:p.amount});else if(b.paid&&b.paidAt)entries.push({id:'batch-'+b.id,date:b.paidAt,kind:'out',source:'Stock purchase',description,amount:b.qty*b.unitCost});}
  for(const e of s.expenses)entries.push({id:'expense-'+e.id,date:e.date,kind:'out',source:e.category,description:e.notes||'Operating expense',amount:e.amount});
  for(const e of s.cashEntries)entries.push({id:'manual-'+e.id,date:e.date,kind:e.kind,source:e.category,description:e.description||'Other cash movement',amount:e.amount});
  entries.sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));
  return {entries,undated:s.orders.filter(o=>o.settled&&!o.settledAt&&!o.collections.length).length+s.batches.filter(b=>b.paid&&!b.paidAt&&!b.payments.length).length};
}

/** Keep the ALOYRI identity fixed for existing and imported workspaces. */
export const fixedBusinessName = (state:State):State => ({...state,businessName:'ALOYRI',orders:state.orders.map(o=>{if(o.settled&&o.collections.length===0)return o;const due=Math.max(0,total(o)-o.courierCost-o.paymentFee),received=o.collections.reduce((n,p)=>n+p.amount,0),settled=due>0&&received>=due-.001;return {...o,settled,settledAt:settled?(o.collections.at(-1)?.date||o.settledAt):undefined}}),batches:state.batches.map(b=>{const total=b.qty*b.unitCost,paidAmount=b.payments.reduce((n,p)=>n+p.amount,0);if(b.paid&&b.payments.length===0)return b;const paid=total>0&&paidAmount>=total-.001;return {...b,paid,paidAt:paid?(b.payments.at(-1)?.date||b.paidAt):undefined}})});
