import { today,shiftDate,stockPosition,batchRemaining,supplierInsight,orderBalance,customerPaidAmount,creditBalance,cashflow,automationSignals,type State } from './crm.ts';
import { workspaceSummary } from './workspace-summary.ts';
import type { PageRequest } from './pagination.ts';
import { pageMetadata } from './pagination.ts';

export const sectionKinds={products:'Inventory',batches:'Inventory',categories:'Inventory',returns:'Inventory',cancelledHolds:'Inventory',holds:'Inventory',purchaseOrders:'Suppliers',suppliers:'Suppliers',tasks:'Follow-ups',collections:'Finances',collectionHistory:'Finances',payables:'Finances',expenses:'Finances',cashflow:'Finances',refundOrders:'Finances',refundHistory:'Finances',credits:'Finances',creditHistory:'Finances',assigned:'Finances',unassigned:'Finances',automation:'Automation',integrity:'Finances'} as const;
export type SectionKind=keyof typeof sectionKinds;
export type SectionOptions={sort?:string;month?:string;range?:string;account?:string};
/** Stable server-side ordering includes an ID tie-breaker for records with equal dates. */
export function sectionRecordIds(s:State,kind:SectionKind,page:PageRequest,options:SectionOptions={}){
 const q=page.q.toLowerCase(),filter=page.status,match=(...values:unknown[])=>!q||values.some(v=>String(v??'').toLowerCase().includes(q));
 const id=(a:{id:string},b:{id:string})=>a.id.localeCompare(b.id),customers=new Map(s.customers.map(c=>[c.id,c])),products=new Map(s.products.map(p=>[p.id,p])),suppliers=new Map(s.suppliers.map(p=>[p.id,p]));
 switch(kind){
 case 'products':{
  const ranks:Record<string,number>={Out:0,Critical:1,Low:2,Healthy:3,Inactive:4};
  const rows=s.products.map(product=>{const p=stockPosition(s,product.id),critical=product.reorderAt>0?Math.max(1,Math.ceil(product.reorderAt/2)):0,health=!product.active?'Inactive':p.available===0?'Out':critical&&p.available<=critical?'Critical':p.available<=product.reorderAt?'Low':'Healthy',batches=s.batches.filter(b=>b.productId===product.id&&b.expiry>today()&&batchRemaining(s,b)>0),expiry=batches.map(b=>b.expiry).sort()[0]||'9999-12-31',value=batches.reduce((n,b)=>n+Math.max(0,batchRemaining(s,b))*b.unitCost,0),movement=s.orders.filter(o=>o.status==='Delivered'&&(o.delivered||o.created)>=shiftDate(-29)).reduce((n,o)=>n+o.items.filter(i=>i.productId===product.id).reduce((x,i)=>x+i.qty,0),0);return {product,...p,health,expiry,value,movement}}).filter(r=>match(r.product.name,r.product.brand,r.product.size,r.product.category,r.product.id,r.health)).filter(r=>filter==='All'||filter==='Low stock'&&['Low','Critical'].includes(r.health)||filter==='Critical'&&r.health==='Critical'||filter==='Out of stock'&&r.health==='Out'||filter==='Healthy'&&r.health==='Healthy'||filter==='Inactive'&&r.health==='Inactive'||filter==='Reserved'&&r.reserved>0||filter==='Return inspection'&&r.returnedPending>0||filter==='Blocked'&&r.blocked>0||filter==='No movement · 30d'&&r.available>0&&r.movement===0||r.product.category===filter);
  rows.sort((a,b)=>{let n=0;switch(options.sort){case 'Available ↑':n=a.available-b.available;break;case 'Available ↓':n=b.available-a.available;break;case 'Expiry soonest':n=a.expiry.localeCompare(b.expiry);break;case '30d movement':n=b.movement-a.movement;break;case 'Stock value':n=b.value-a.value;break;case 'Name A–Z':break;default:n=ranks[a.health]-ranks[b.health]||a.available-b.available}return n||a.product.name.localeCompare(b.product.name)||id(a.product,b.product)});return rows.map(r=>r.product.id);
 }
 case 'batches':return s.batches.filter(b=>filter==='All'||filter==='Expiring'&&b.expiry>today()&&b.expiry<=shiftDate(90)&&batchRemaining(s,b)>0||filter==='Expired'&&b.expiry<=today()&&batchRemaining(s,b)>0||filter==='Received this month'&&b.received.slice(0,7)===(options.month||today().slice(0,7))).filter(b=>match(products.get(b.productId)?.name,b.invoice)).sort((a,b)=>a.expiry.localeCompare(b.expiry)||id(a,b)).map(b=>b.id);
 case 'categories':return s.productCategories.filter(c=>match(c)).sort().map(c=>c);
 case 'returns':return s.orders.filter(o=>o.status==='Returned'&&!o.restocked).sort((a,b)=>(a.returnedAt||a.created).localeCompare(b.returnedAt||b.created)||id(a,b)).map(o=>o.id);
 case 'cancelledHolds':return [...new Set(s.inventoryHolds.filter(h=>!h.releasedAt&&h.source==='Cancelled'&&h.type==='Quarantine').map(h=>h.sourceOrderId).filter((x):x is string=>Boolean(x)))].sort();
 case 'holds':return s.inventoryHolds.filter(h=>!h.releasedAt&&!(h.source==='Cancelled'&&h.type==='Quarantine')).sort((a,b)=>a.date.localeCompare(b.date)||id(a,b)).map(h=>h.id);
 case 'purchaseOrders':return s.purchaseOrders.filter(po=>{const supplier=suppliers.get(po.supplierId),overdue=['Sent','Part received'].includes(po.status)&&po.expected<today();return (filter==='All'||filter===po.status||filter==='Overdue'&&overdue)&&match(po.number,supplier?.name,supplier?.contact,supplier?.phone,po.status,po.notes,...po.items.map(i=>products.get(i.productId)?.name))}).sort((a,b)=>Number(['Sent','Part received'].includes(b.status)&&b.expected<today())-Number(['Sent','Part received'].includes(a.status)&&a.expected<today())||a.expected.localeCompare(b.expected)||b.created.localeCompare(a.created)||id(a,b)).map(po=>po.id);
 case 'suppliers':return s.suppliers.filter(p=>match(p.name,p.contact,p.phone,p.email,p.address,p.notes)).map(supplier=>({supplier,open:supplierInsight(s,supplier.id).activePurchaseOrders.length})).sort((a,b)=>b.open-a.open||a.supplier.name.localeCompare(b.supplier.name)||id(a.supplier,b.supplier)).map(r=>r.supplier.id);
 case 'tasks':{const orders=new Map(s.orders.map(o=>[o.id,o])),rank={High:0,Normal:1,Low:2};return s.tasks.filter(t=>{const c=customers.get(t.customerId),o=orders.get(t.orderId);return (filter==='All'||filter==='Open'&&!t.done||filter==='Completed'&&t.done||filter==='Overdue'&&!t.done&&t.due<today()||filter==='Today'&&!t.done&&t.due===today()||filter==='Next 7 days'&&!t.done&&t.due>today()&&t.due<=shiftDate(7)||filter==='Follow-up'&&t.kind==='Follow-up'||filter==='Replenishment'&&t.kind==='Replenishment'||filter==='High priority'&&!t.done&&t.priority==='High')&&match(t.title,t.kind,t.priority,t.channel,t.notes,c?.name,c?.phone,o?.number)}).sort((a,b)=>Number(a.done)-Number(b.done)||a.due.localeCompare(b.due)||rank[a.priority]-rank[b.priority]||a.title.localeCompare(b.title)||id(a,b)).map(t=>t.id)}
 case 'collections':return s.orders.filter(o=>(o.status==='Delivered'||o.payment!=='COD'&&!['Cancelled','Returned'].includes(o.status))&&orderBalance(o)>.001).sort((a,b)=>(a.delivered||a.created).localeCompare(b.delivered||b.created)||id(a,b)).map(o=>o.id);
 case 'collectionHistory':return s.orders.flatMap(o=>o.collections.map(p=>({id:o.id+':'+p.id,date:p.date}))).sort((a,b)=>b.date.localeCompare(a.date)||id(a,b)).map(r=>r.id);
 case 'payables':return s.batches.filter(b=>!b.paid||b.payments.length>0).filter(b=>b.qty*b.unitCost-b.payments.reduce((n,p)=>n+p.amount,0)>.001).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')||id(a,b)).map(b=>b.id);
 case 'expenses':return s.expenses.filter(e=>!options.month||e.date.slice(0,7)===options.month).sort((a,b)=>b.date.localeCompare(a.date)||id(a,b)).map(e=>e.id);
 case 'cashflow':return cashflow(s).entries.filter(e=>options.range==='all'||e.date>=shiftDate(-29)).sort((a,b)=>b.date.localeCompare(a.date)||id(a,b)).map(e=>e.id);
 case 'refundOrders':return s.orders.filter(o=>['Returned','Cancelled'].includes(o.status)&&customerPaidAmount(o)>0).sort((a,b)=>(b.returnedAt||b.created).localeCompare(a.returnedAt||a.created)||id(a,b)).map(o=>o.id);
 case 'refundHistory':return [...s.customerRefunds].sort((a,b)=>b.date.localeCompare(a.date)||id(a,b)).map(r=>r.id);
 case 'credits':return s.returnSettlements.filter(r=>creditBalance(s,r)>0).sort((a,b)=>a.date.localeCompare(b.date)||id(a,b)).map(r=>r.id);
 case 'creditHistory':return [...s.creditUses].sort((a,b)=>b.date.localeCompare(a.date)||id(a,b)).map(r=>r.id);
 case 'assigned':case 'unassigned':{const opening=s.accountOpenings.find(a=>a.account===options.account),links=new Map(s.accountMatches.map(m=>[m.entryId,m]));return opening?cashflow(s).entries.filter(e=>e.date>=opening.date&&(kind==='assigned'?links.get(e.id)?.account===options.account:!links.has(e.id))).sort((a,b)=>b.date.localeCompare(a.date)||id(a,b)).map(e=>e.id):[]}
 case 'integrity':return workspaceSummary(s,'owner').report.integrityIssues.map(issue=>[issue.level,issue.title,issue.detail,issue.tab].join('|'));
 case 'automation':return automationSignals(s).map(x=>x.key);
 }
}
export function sectionPage(s:State,kind:SectionKind,page:PageRequest,options:SectionOptions={}){const ids=sectionRecordIds(s,kind,page,options);return {ids:ids.slice((page.page-1)*page.pageSize,page.page*page.pageSize),pagination:pageMetadata(page,ids.length)}}
