import { getAppUser, checkOrigin } from '@/app/local-auth';
import { AccessDenied, resolveWorkspace } from '@/app/team-access';
import { database } from '@/db/raw';
import { fixedBusinessName, stateSchema, validateRelations } from '@/lib/crm';
import { roleCanBackup } from '@/lib/roles';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){
 try{const user=await getAppUser();if(!user)return response({error:'Please sign in.'},401);const {ownerId,role}=await resolveWorkspace(user);if(!roleCanBackup(role))return response({error:'Only the business owner can create a full backup.'},403);const row=await database().prepare('SELECT data,version,updated_at FROM crm_workspaces WHERE owner_id=?').bind(ownerId).first<{data:string;version:number;updated_at:string}>();if(!row)return response({error:'Workspace not found.'},404);const data=fixedBusinessName(stateSchema.parse(JSON.parse(row.data)));return response({format:'aloyri-workspace-backup',schemaVersion:1,createdAt:new Date().toISOString(),workspaceVersion:row.version,workspaceUpdatedAt:row.updated_at,data});}catch(e){if(e instanceof AccessDenied)return response({error:e.message},403);return response({error:'Could not create backup.'},503)}}
export async function POST(request:Request){
 try{const user=await getAppUser();if(!user)return response({error:'Please sign in.'},401);if(!checkOrigin(request))return response({error:'Invalid request origin.'},403);const {ownerId,role}=await resolveWorkspace(user);if(!roleCanBackup(role))return response({error:'Only the business owner can restore a backup.'},403);const text=await request.text();if(text.length>1900000)return response({error:'Backup is too large.'},413);let body:any;try{body=JSON.parse(text)}catch{return response({error:'Invalid backup JSON.'},400)}if(body?.confirmation!=='RESTORE ALOYRI')return response({error:'Type RESTORE ALOYRI to confirm.'},400);if(body?.backup?.format!=='aloyri-workspace-backup'||body.backup.schemaVersion!==1)return response({error:'This is not a supported ALOYRI workspace backup.'},400);const restored=fixedBusinessName(stateSchema.parse(body.backup.data));validateRelations(restored);const db=database();const row=await db.prepare('SELECT version FROM crm_workspaces WHERE owner_id=?').bind(ownerId).first<{version:number}>();if(!row)return response({error:'Workspace not found.'},404);const now=new Date().toISOString();const result=await db.prepare('UPDATE crm_workspaces SET data=?,version=version+1,updated_at=? WHERE owner_id=? AND version=?').bind(JSON.stringify(restored),now,ownerId,row.version).run();if(!result.meta.changes)return response({error:'Workspace changed while restoring. Try again.'},409);await db.prepare('CREATE TABLE IF NOT EXISTS crm_audit_log (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, actor_id TEXT NOT NULL, actor_name TEXT NOT NULL, role TEXT NOT NULL, summary TEXT NOT NULL, sections TEXT NOT NULL, created_at TEXT NOT NULL)').run();await db.prepare('INSERT INTO crm_audit_log (id,owner_id,actor_id,actor_name,role,summary,sections,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),ownerId,user.userId,user.displayName||user.email,role,'Restored full workspace backup',JSON.stringify(['backup restore']),now).run();return response({ok:true,version:row.version+1});}catch(e){if(e instanceof AccessDenied)return response({error:e.message},403);console.error('Backup restore failed',e);return response({error:e instanceof Error?e.message:'Could not restore backup.'},400)}}
